nama = input("Saipul anuar: ")
usia = input("18: ")
alamat = input("dsn.petaling jaya: ")
hobi = input("sepak bola: ")
print("\n=== Biodata Anda ===")
print(f"Nama   : {nama}")
print(f"Usia   : {usia} tahun")
print(f"Alamat : {alamat}")
print(f"Hobi   : {hobi}")